#!/bin/sh
#rm *.o *.cmx *.cmi
# rm *.cmo

# ignore: CommonRank.ml

FILES="Common.ml History.ml Monoid.ml Pattern.ml ReadPattern.ml WhichTest.ml CorePattern.ml Simulate.ml SimStep.ml SimCont.ml SimFlush.ml SimRank.ml UnitTest.ml UnitTestStep.ml UnitTestCont.ml UnitTestFlush.ml UnitTestRank.ml Testab.ml Testnull.ml"

#FILES="SimRank.ml"

FILES2="Main.ml"

optPP_I="$(ocamlfind query -i-format type_conv) $(ocamlfind query -i-format sexplib)"
optPP="camlp4o $optPP_I pa_type_conv.cma pa_sexp_conv.cma"
optPACKAGE="camomile,core,core_extended,type_conv,sexplib"
#optI=$(ocamlfind query -i-format sexplib)
#optL=$(ocamlfind query -l-format sexplib)

compileFile () {
#  echo ocamlfind ocamlopt $2 -w +A-4 -annot -pp "camlp4o -I `ocamlfind query type_conv` -I `ocamlfind query sexplib` pa_type_conv.cma pa_sexp_conv.cma" -I `ocamlfind query sexplib` -thread -package $optPACKAGE /Users/chrisk/local//godi/lib/ocaml/pkg-lib/sexplib/sexplib.cmxa -c $1;
       ocamlfind ocamlopt $2 -w +A-4 -annot -pp "camlp4o -I `ocamlfind query type_conv` -I `ocamlfind query sexplib` pa_type_conv.cma pa_sexp_conv.cma" -I `ocamlfind query sexplib` -thread -package $optPACKAGE /Users/chrisk/local/godi/lib/ocaml/pkg-lib/sexplib/sexplib.cmxa -c $1;
}

for i in $FILES; do
    if [ -r "${i}i" ]; then
        echo "${i}i";
        compileFile "${i}i"; 
        echo "$i"
        compileFile "$i"
    else
        echo "$i to ${i}i"
        compileFile "$i" -i  > ${i}i
        compileFile "${i}i"; 
        compileFile "$i"
    fi
done

for i in $FILES2; do
    echo "$i"
    compileFile "$i"
done

# These are pretty universal
libs="Common.cmx History.cmx Monoid.cmx Pattern.cmx ReadPattern.cmx WhichTest.cmx CorePattern.cmx Simulate.cmx"

ocamlfind ocamlopt -thread -o Main -linkpkg -package "$optPACKAGE" $libs SimStep.cmx Main.cmx

#rm UnitTest
ocamlfind ocamlopt -thread -o UnitTest -linkpkg -package $optPACKAGE $libs UnitTest.cmx

ocamlfind ocamlopt -thread -o UnitTestStep -linkpkg -package "$optPACKAGE" $libs SimStep.cmx UnitTestStep.cmx

ocamlfind ocamlopt -thread -o UnitTestCont -linkpkg -package "$optPACKAGE" $libs SimStep.cmx SimCont.cmx UnitTestCont.cmx

ocamlfind ocamlopt -thread -o UnitTestFlush -linkpkg -package "$optPACKAGE" $libs SimStep.cmx SimCont.cmx SimFlush.cmx UnitTestFlush.cmx

ocamlfind ocamlopt -thread -o UnitTestRank -linkpkg -package "$optPACKAGE" $libs SimStep.cmx SimRank.cmx UnitTestRank.cmx

ocamlfind ocamlopt -thread -o Testab -linkpkg -package "$optPACKAGE" $libs SimStep.cmx Testab.cmx

ocamlfind ocamlopt -thread -o Testnull -linkpkg -package "$optPACKAGE" $libs SimStep.cmx Testnull.cmx

